### PR TITLE
Hello world

### PR DESCRIPTION
**Pull request by achuie**
This PR sets up the initial project, along with some infra for reproducible development environments using Nix [(cf)](https://nixos.org/manual/nix/unstable/command-ref/new-cli/nix3-develop.html). See also [django intro](https://docs.djangoproject.com/en/4.1/intro/tutorial01/).

Test with:
```
cd cookbookapp
python manage.py runserver
```
then browse to `localhost:8000/recipes`

### CODE REVIEW

**Review by the-tarin — COMMENTED** [review]
Looks good. Do we need to include 'Search Bar' as an app, or could that be a separate component file in cookbookapp?

**Comment by achuie** [comment]
> Looks good. Do we need to include 'Search Bar' as an app, or could that be a separate component file in cookbookapp?

I think search should be integrated, as we don't intend for it to be a whole different "mode" of interacting with recipes.

**Review by the-tarin — APPROVED** [review]
Looks good. Basic structure with cookbookapp and recipes app, so it's quite standard. Code compiles and we are able to successfully host the website locally.

**Review by jilaada — APPROVED** [review]
LGTM

**Pull request merged**
